def options(opt):
        opt.load('compiler_cxx')
def configure(cnf):
        cnf.load('compiler_cxx')
def build(bld):
        bld(features='cxx cxxprogram', source='../gpio.cpp ../Bitoperation.cpp mpu.cpp Test/test.cpp'  , target='app')
        
        
        
        
        
        
